spring.application.name=greet
server.port=9091
#spring.boot.admin.client.url=http://localhost:1111/
spring.config.import: optional:configserver:http://localhost:2222
management.endpoints.web.exposure.include=*,refresh
